site:
    title: harmen.ch
    url: https://www.harmen.ch
content:
  sources:
    - url: ./
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true