site:
    title: docs.harmen.ch
    url: https://docs.harmen.ch
    start_page: docs.harmen.ch:ROOT:index.adoc
    robots: allow
content:
  sources:
    - url: ./
#    - url: /Users/harmen/repositories/ch-harmen-echo
#      start_path: docs
    - url: https://github.com/harmenweber/asciidoc-templates
      start_path: docs
asciidoc:
  attributes:
    sectnums: ''
    sectanchors: ''
    icons: 'font'
    icon-set: 'far'
    page-pagination: ''
    experimental: ''
    table-frame: 'none@'
    table-grid: 'rows@'
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
ui:
  bundle:
    url: https://d18du1025xydad.cloudfront.net/ui-bundle.zip
    snapshot: true
  supplemental_files: ./node_modules/@antora/lunr-extension/supplemental_ui
output:
  clean: true
runtime:
  fetch: true